# SPDX-License-Identifier: Apache-2.0
sonar.projectKey=rdzehtsiar_corpusforge
sonar.organization=raman-dzehtsiar
sonar.projectName=Corpus Forge
# sonar.sources=src
# sonar.tests=tests
sonar.sourceEncoding=UTF-8
sonar.rust.lcov.reportPaths=lcov.info
sonar.exclusions=target/**,qodana.sarif.json
